# Generated by Django 3.2 on 2022-01-26 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_rename_iotclass_iotmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotmodel',
            name='schedule',
            field=models.TimeField(default=datetime.datetime(2022, 1, 26, 17, 27, 40, 902391, tzinfo=utc)),
        ),
    ]
