# Generated by Django 3.2 on 2022-01-26 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_iotmodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iotmodel',
            name='schedule',
            field=models.TimeField(default=datetime.datetime(2022, 1, 26, 17, 35, 40, 908529, tzinfo=utc)),
        ),
    ]
