# Generated by Django 3.2 on 2022-01-26 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20220126_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 40, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.TextField(),
        ),
    ]
