# Generated by Django 4.0 on 2021-12-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created',
            field=models.DateField(default='2021-12-12'),
        ),
    ]
