# Generated by Django 3.2 on 2021-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='use_request',
            field=models.BooleanField(default=False),
        ),
    ]
