# Generated by Django 3.2 on 2022-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_use_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created',
            field=models.DateField(default='2022-01-26'),
        ),
    ]
